# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeHistory < Formula
  desc "CLI tool for programmatic access to Claude Code's agent history storage"
  homepage "https://github.com/randlee/claude-history"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/randlee/claude-history/releases/download/v0.3.0/claude-history_0.3.0_darwin_amd64.tar.gz"
      sha256 "d7462d09037837084a566ba8f2522e04f2b7f1242905c6f1f28b243280ce5637"

      def install
        bin.install "claude-history"
      end
    end
    on_arm do
      url "https://github.com/randlee/claude-history/releases/download/v0.3.0/claude-history_0.3.0_darwin_arm64.tar.gz"
      sha256 "ada13eec0fc1b60a1e727e4b7e2d9c5fd28524db7c53681ba4649d947e2ff8ba"

      def install
        bin.install "claude-history"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/randlee/claude-history/releases/download/v0.3.0/claude-history_0.3.0_linux_amd64.tar.gz"
        sha256 "fed5a9f402c1fc60e1dd0930b146f5637dfbb3044cb19eb39a910b8f95fe5dd2"

        def install
          bin.install "claude-history"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/randlee/claude-history/releases/download/v0.3.0/claude-history_0.3.0_linux_arm64.tar.gz"
        sha256 "db7349ac64e4d0561004bfa45dfae658b87a2b55446b17d1f5863a94a7290676"

        def install
          bin.install "claude-history"
        end
      end
    end
  end

  test do
    system "#{bin}/claude-history", "--version"
  end
end
