# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sc < Formula
  desc "Dolt-backed package manager for Claude Code skills"
  homepage "https://github.com/randlee/synaptic-canvas"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/randlee/synaptic-canvas-dolt/releases/download/v0.2.1/sc_0.2.1_darwin_amd64.tar.gz"
      sha256 "32a76d53833a748c0f0e0d42c4fff0477e6a47178742e7d0d5f8753b1e006c66"

      define_method(:install) do
        bin.install "sc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/randlee/synaptic-canvas-dolt/releases/download/v0.2.1/sc_0.2.1_darwin_arm64.tar.gz"
      sha256 "878c63aa9054b33ba29026b3728ffd9716c700e27f646600307e2b16ec6ceb43"

      define_method(:install) do
        bin.install "sc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/randlee/synaptic-canvas-dolt/releases/download/v0.2.1/sc_0.2.1_linux_amd64.tar.gz"
      sha256 "a16e73e087ca085d064ba1607105c32a98771827261ce8593a382fa2335955bf"
      define_method(:install) do
        bin.install "sc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/randlee/synaptic-canvas-dolt/releases/download/v0.2.1/sc_0.2.1_linux_arm64.tar.gz"
      sha256 "8e9663ec820b9f79d69e40289a1bed53d198e63f773fadcdcd3d01cad9817cc4"
      define_method(:install) do
        bin.install "sc"
      end
    end
  end
end
