# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sc < Formula
  desc "Dolt-backed package manager for Claude Code skills"
  homepage "https://github.com/randlee/synaptic-canvas-dolt"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/randlee/synaptic-canvas-dolt/releases/download/v0.4.0/sc_0.4.0_darwin_amd64.tar.gz"
      sha256 "404109be23e9dd0b43ee7c2ebdb1d09c53626aacc024220ad35be1d9eb0efaa5"

      define_method(:install) do
        bin.install "sc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/randlee/synaptic-canvas-dolt/releases/download/v0.4.0/sc_0.4.0_darwin_arm64.tar.gz"
      sha256 "35ebf26b98e7181f155f0f2495ebe1520ca53d6560b746e868670d436d49d073"

      define_method(:install) do
        bin.install "sc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/randlee/synaptic-canvas-dolt/releases/download/v0.4.0/sc_0.4.0_linux_amd64.tar.gz"
      sha256 "15dd50afe508a9571e35c4aa88b9465b0c5786f20cdf2bd4bdafba35a415bcc2"
      define_method(:install) do
        bin.install "sc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/randlee/synaptic-canvas-dolt/releases/download/v0.4.0/sc_0.4.0_linux_arm64.tar.gz"
      sha256 "41a86981abb10f04bf82b54f8f9537a408bec592753bd207aaf75883ecda3e13"
      define_method(:install) do
        bin.install "sc"
      end
    end
  end
end
